
package Project_Panel;

import DatabaseConnection.DBConnectioncode;
import com.lowagie.text.BadElementException;
import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.Element;
import com.lowagie.text.Font;
import com.lowagie.text.PageSize;
import com.lowagie.text.Paragraph;
import com.lowagie.text.Phrase;
import com.lowagie.text.pdf.PdfContentByte;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.coobird.thumbnailator.Thumbnails;


public class Panel_TeacherInformation extends javax.swing.JPanel {

    //Variaable for Database Connection
    
    Connection con;
    PreparedStatement prepstmnt = null;
    ResultSet res = null;
    
    //variable for image
    
    private ImageIcon format=null;
    String teacherfile=null;
    byte[] teacher_image=null;
    
    
    public Panel_TeacherInformation() {
        initComponents();
       
        
        //Database Connection Code call
        try {
            con = DBConnectioncode.DBConnectioncode();

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Panel_TeacherInformation.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        //This code for show Teacher Information Table on the starting
     
        ShowTable();
    }
    
    public void Refresh(){
        txtName.setText(null);
        jComboDesignation.setSelectedItem("Select");
        txtmobile.setText(null);
        txtemail.setText(null);
        txtareaaddress.setText(null);
        txtimagepath.setText(null);
        lblTeacherimage.setIcon(null);
    }
    
    
    public final void ShowTable()
    {
         try{
            DefaultTableModel tb = (DefaultTableModel)jTableTeacher.getModel();
            String sqlSearch = "SELECT * FROM Teacher_Information";
            prepstmnt = con.prepareStatement(sqlSearch);
            res = prepstmnt.executeQuery();
            
            while(res.next())
            {
                String Name = res.getString("Teacher_Name");
                String Desig = res.getString("Teacher_Desig");
                String Mobile = res.getString("Teacher_Mobile");
                String Email = res.getString("Teacher_Email");
                String Add = res.getString("Teacher_Address");
               
                
                
                tb.addRow(new Object[]{Name,Desig,Mobile,Email,Add});
                
            }
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    
    public void TableRefresh()
    {
        try{
            DefaultTableModel tb = (DefaultTableModel)jTableTeacher.getModel();
         int row=jTableTeacher.getRowCount();
         for(int i=row-1;i>=0;i--)
         {
             tb.removeRow(i);
         }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel35 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtmobile = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtareaaddress = new javax.swing.JTextArea();
        jComboDesignation = new javax.swing.JComboBox();
        jPanel33 = new javax.swing.JPanel();
        jPanel36 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        lblTeacherimage = new javax.swing.JLabel();
        txtimagepath = new javax.swing.JTextField();
        btnAttach = new javax.swing.JButton();
        jPanel75 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableTeacher = new javax.swing.JTable();
        jPanel74 = new javax.swing.JPanel();
        txt_Search = new javax.swing.JTextField();
        btnSeach = new javax.swing.JButton();
        jPanel37 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnAddnew = new javax.swing.JButton();
        btnprint = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        jPanel35.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel32.setText("Name :");

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel33.setText("Designation :");

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel34.setText("Mobile No :");

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel35.setText("E-mail :");

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel36.setText("Address :");

        txtName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        txtmobile.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        txtemail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtareaaddress.setColumns(20);
        txtareaaddress.setRows(5);
        jScrollPane4.setViewportView(txtareaaddress);

        jComboDesignation.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jComboDesignation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Cheif Instructor", "Instructor", "Jr. Instructor", "Guest Teacher" }));

        javax.swing.GroupLayout jPanel35Layout = new javax.swing.GroupLayout(jPanel35);
        jPanel35.setLayout(jPanel35Layout);
        jPanel35Layout.setHorizontalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel35Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtName)
                    .addComponent(txtmobile)
                    .addComponent(txtemail)
                    .addComponent(jScrollPane4)
                    .addComponent(jComboDesignation, 0, 216, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel35Layout.setVerticalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel35Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboDesignation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel33.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel33.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane1.setLayer(lblTeacherimage, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTeacherimage, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTeacherimage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel36Layout = new javax.swing.GroupLayout(jPanel36);
        jPanel36.setLayout(jPanel36Layout);
        jPanel36Layout.setHorizontalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        jPanel36Layout.setVerticalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        jPanel33.add(jPanel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 170, -1));
        jPanel33.add(txtimagepath, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 170, 30));

        btnAttach.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAttach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Panel/mail-attachment.png"))); // NOI18N
        btnAttach.setText("Attach");
        btnAttach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttachActionPerformed(evt);
            }
        });
        jPanel33.add(btnAttach, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 227, 170, 30));

        jPanel75.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTableTeacher.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "        Name", "       Designation", "       Mobile", "       E-mail", "       Address"
            }
        ));
        jTableTeacher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTeacherMouseClicked(evt);
            }
        });
        jTableTeacher.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableTeacherKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableTeacherKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(jTableTeacher);

        javax.swing.GroupLayout jPanel75Layout = new javax.swing.GroupLayout(jPanel75);
        jPanel75.setLayout(jPanel75Layout);
        jPanel75Layout.setHorizontalGroup(
            jPanel75Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel75Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel75Layout.setVerticalGroup(
            jPanel75Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel75Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel74.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txt_Search.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_SearchActionPerformed(evt);
            }
        });
        txt_Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_SearchKeyReleased(evt);
            }
        });

        btnSeach.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSeach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Panel/search.gif"))); // NOI18N
        btnSeach.setText("Search");

        javax.swing.GroupLayout jPanel74Layout = new javax.swing.GroupLayout(jPanel74);
        jPanel74.setLayout(jPanel74Layout);
        jPanel74Layout.setHorizontalGroup(
            jPanel74Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel74Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_Search, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnSeach)
                .addContainerGap())
        );
        jPanel74Layout.setVerticalGroup(
            jPanel74Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel74Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel74Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSeach, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel37.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Panel/save2.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Panel/Trash-can16.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Panel/Update.png"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnAddnew.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddnew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Panel/user-male-add.png"))); // NOI18N
        btnAddnew.setText("Add New");
        btnAddnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddnewActionPerformed(evt);
            }
        });

        btnprint.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnprint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Panel/Print.png"))); // NOI18N
        btnprint.setText("Print");
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });

        btnRefresh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Panel/refresh.png"))); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel37Layout = new javax.swing.GroupLayout(jPanel37);
        jPanel37.setLayout(jPanel37Layout);
        jPanel37Layout.setHorizontalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel37Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel37Layout.createSequentialGroup()
                        .addComponent(btnAddnew)
                        .addGap(18, 18, 18)
                        .addComponent(btnprint, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRefresh)
                        .addContainerGap())
                    .addGroup(jPanel37Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate)
                        .addGap(22, 22, 22))))
        );
        jPanel37Layout.setVerticalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel37Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddnew, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnprint, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addComponent(jPanel33, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(404, 404, 404)
                        .addComponent(jPanel74, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel75, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jPanel37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel33, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel74, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jPanel75, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAttachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttachActionPerformed
//Attach Image


        JFileChooser chooser = new JFileChooser();
        
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int pic = chooser.showOpenDialog(Panel_TeacherInformation.this);
        
        
        if (pic == JFileChooser.APPROVE_OPTION) {

        File f = chooser.getSelectedFile();
        ImageIcon image = new ImageIcon(f.getAbsolutePath());
        Rectangle rect = lblTeacherimage.getBounds();
        Image scaledimage = image.getImage().getScaledInstance(rect.width, rect.height, Image.SCALE_DEFAULT);
        image = new ImageIcon(scaledimage);
        lblTeacherimage.setIcon(image);
        
        teacherfile = f.getAbsolutePath();//declared filename variable
        txtimagepath.setText(teacherfile);//location is variable name of textfield with attach button
        
        }
        else{
            JOptionPane.showMessageDialog(null, "Cancelled by User");
        }
        try {
            File image = new File(teacherfile);
            BufferedImage bufferedimage = ImageIO.read(image);
            BufferedImage thumbnail = Thumbnails.of(bufferedimage).size(200, 200).asBufferedImage();
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            ImageIO.write(thumbnail, "jpeg", bos);
            
            InputStream is = new ByteArrayInputStream(bos.toByteArray());
            byte[] buf = new byte[1024];
            for (int readNum; (readNum = is.read(buf)) != -1;) {
                bos.write(buf, 0, readNum);
                System.out.println("Read " + readNum + " bytes");
            }
            teacher_image = bos.toByteArray();//declared variable person_image
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_btnAttachActionPerformed

    private void jTableTeacherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTeacherMouseClicked
      
        
        try{
            int row = jTableTeacher.getSelectedRow();
            String Table_Click = (jTableTeacher.getModel().getValueAt(row, 0).toString());
            String sqlSearch = "SELECT * FROM Teacher_Information WHERE Teacher_Name ='"+Table_Click+"'";
            prepstmnt = con.prepareStatement(sqlSearch);
            res = prepstmnt.executeQuery();
            
            
            while(res.next())
            {
                String Name = res.getString("Teacher_Name");
                String Desig = res.getString("Teacher_Desig");
                String Mobile = res.getString("Teacher_Mobile");
                String Email = res.getString("Teacher_Email");
                String Add = res.getString("Teacher_Address");
                
                
                txtName.setText(Name);
                jComboDesignation.setSelectedItem(Desig);
                txtmobile.setText(Mobile);
                txtemail.setText(Email);
                txtareaaddress.setText(Add);
                
               
            }
        }catch(SQLException | NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jTableTeacherMouseClicked

    private void jTableTeacherKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableTeacherKeyReleased
     
        if(evt.getKeyCode()==KeyEvent.VK_UP || evt.getKeyCode()==KeyEvent.VK_DOWN)
        {
            try{
            int row = jTableTeacher.getSelectedRow();
            String Table_Click = (jTableTeacher.getModel().getValueAt(row, 0).toString());
            String sqlSearch = "SELECT * FROM Teacher_Information WHERE Teacher_Name ='"+Table_Click+"'";
            prepstmnt = con.prepareStatement(sqlSearch);
            res = prepstmnt.executeQuery();
            
            
            while(res.next())
            {
                String Name = res.getString("Teacher_Name");
                String Desig = res.getString("Teacher_Desig");
                String Mobile = res.getString("Teacher_Mobile");
                String Email = res.getString("Teacher_Email");
                String Add = res.getString("Teacher_Address");
                
                
                txtName.setText(Name);
                jComboDesignation.setSelectedItem(Desig);
                txtmobile.setText(Mobile);
                txtemail.setText(Email);
                txtareaaddress.setText(Add);
                
               
            }
        }catch(SQLException | NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        }

        
    }//GEN-LAST:event_jTableTeacherKeyReleased

    private void txt_SearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_SearchKeyReleased

        //Refresh();
        try{
            DefaultTableModel tb = (DefaultTableModel)jTableTeacher.getModel();
         int row=jTableTeacher.getRowCount();
         for(int i=row-1;i>=0;i--)
         {
            tb.removeRow(i);
         }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
        try{
            DefaultTableModel tb = (DefaultTableModel)jTableTeacher.getModel();
            String sqlSearch = "SELECT * FROM Teacher_Information where Teacher_Name like '%"+txt_Search.getText()+"%'";
            prepstmnt = con.prepareStatement(sqlSearch);
            res = prepstmnt.executeQuery();
            
            while(res.next())
            {
                String Name = res.getString("Teacher_Name");
                String Desig = res.getString("Teacher_Desig");
                String Mobile = res.getString("Teacher_Mobile");
                String Email = res.getString("Teacher_Email");
                String Add = res.getString("Teacher_Address");
               
                
                
                tb.addRow(new Object[]{Name,Desig,Mobile,Email,Add});
                
            }
            
        }catch(Exception e)
        {
           JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_txt_SearchKeyReleased

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
       
        try{
            String sqlsave = "INSERT INTO  Teacher_Information(Teacher_Name,Teacher_Desig,Teacher_Mobile,Teacher_Email,Teacher_Address) values(?,?,?,?,?)";

                prepstmnt=con.prepareStatement(sqlsave);
                
                prepstmnt.setString(1,txtName.getText());
                prepstmnt.setString(2, (String) jComboDesignation.getSelectedItem());
                prepstmnt.setString(3,txtmobile.getText());
                prepstmnt.setString(4,txtemail.getText());
                prepstmnt.setString(5,txtareaaddress.getText());

                
                
            int n=prepstmnt.executeUpdate();
            if(n>0)
            {
                JOptionPane.showMessageDialog(this,"Data Saved ");
            }
        }catch(SQLException | HeadlessException e)
        {
            JOptionPane.showMessageDialog(this, e);
        }
        
        
        TableRefresh();
        
        ShowTable();
        
        Refresh();
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

      int msg = JOptionPane.YES_NO_OPTION;

        int result = JOptionPane.showConfirmDialog(null, "Are u Sure?", "Confirm ? ", msg);

        if (result == 0) {
            try {
                String sqlDelete = "DELETE from Teacher_Information where Teacher_Name = ?";

                prepstmnt = con.prepareStatement(sqlDelete);

                prepstmnt.setString(1, txtName.getText());

                int i = prepstmnt.executeUpdate();
                if (i > 0) {
                    JOptionPane.showMessageDialog(this, "Deleted Sucessfully!");
                }
            } catch (Exception  e) 
            {

            }
        
        TableRefresh();
        
        ShowTable();
        
        Refresh();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed

        //Update
       
            try{
                String sqlQry="UPDATE Teacher_Information SET Teacher_Desig= ?,Teacher_Mobile = ?, Teacher_Email = ?,Teacher_Address = ? WHERE Teacher_Name = ?";
                
                prepstmnt = con.prepareStatement(sqlQry);
                
                prepstmnt.setString(1, jComboDesignation.getSelectedItem().toString());
                prepstmnt.setString(2, txtmobile.getText());
                prepstmnt.setString(3, txtemail.getText());
                prepstmnt.setString(4, txtareaaddress.getText());

                prepstmnt.setString(5, txtName.getText());

                int i = prepstmnt.executeUpdate();

                if (i > 0) {
                    JOptionPane.showMessageDialog(this, "DATABAE UPDATED");
                }
            }catch(SQLException | HeadlessException e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
            
            
            TableRefresh();
            
            ShowTable();
            
            Refresh();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnAddnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddnewActionPerformed
        Refresh();
    }//GEN-LAST:event_btnAddnewActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        Refresh();
        
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void jTableTeacherKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableTeacherKeyPressed
       
        if(evt.getKeyCode()==KeyEvent.VK_UP || evt.getKeyCode()==KeyEvent.VK_DOWN)
        {
            try{
            int row = jTableTeacher.getSelectedRow();
            String Table_Click = (jTableTeacher.getModel().getValueAt(row, 0).toString());
            String sqlSearch = "SELECT * FROM teacher_information WHERE Teacher_Name ='"+Table_Click+"'";
            prepstmnt = con.prepareStatement(sqlSearch);
            res = prepstmnt.executeQuery();
            
            
            while(res.next())
            {
                String Name = res.getString("Teacher_Name");
                String Desig = res.getString("Teacher_Desig");
                String Mobile = res.getString("Teacher_Mobile");
                String Email = res.getString("Teacher_Email");
                String Add = res.getString("Teacher_Address");
                
                
                txtName.setText(Name);
                jComboDesignation.setSelectedItem(Desig);
                txtmobile.setText(Mobile);
                txtemail.setText(Email);
                txtareaaddress.setText(Add);
                
               
            }
        }catch(SQLException | NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        }
    }//GEN-LAST:event_jTableTeacherKeyPressed

    
    void print_Teachers_Information() throws SQLException, BadElementException, IOException {
        // con = Connect.ConnectDB();
        Document document = new Document(PageSize.A4.rotate());
       // Document document = new Document(PageSize.A4);
        Font ff1 = new Font(Font.BOLD, 13);
        ff1.setStyle(Font.UNDERLINE);
        ff1.setColor(Color.BLACK);
        ff1.setStyle(Font.BOLD);
        
        Font ff5 = new Font(Font.BOLD, 18);
        ff5.setStyle(Font.UNDERLINE);
        ff5.setColor(Color.BLACK);
        ff5.setStyle(Font.BOLD);
        Font ff3 = new Font(Font.NORMAL, 11);
        ff3.setStyle(Font.COURIER);
        ff3.setColor(Color.BLACK);
        Font ff4 = new Font(Font.BOLD, 10);
        ff4.setStyle(Font.NORMAL);
        ff4.setColor(Color.BLACK);

        

        Paragraph paragraph3 = new Paragraph("\n");         
        paragraph3.setAlignment(Element.ALIGN_CENTER);
       

        try {

            PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream("Report.pdf"));

            document.open();

            PdfContentByte cb = writer.getDirectContent();

            PdfPTable table = new PdfPTable(2);

            PdfPCell cell5 = new PdfPCell();

            String Name="",Desig="",Mobile="",Email="",Add="";

          
            
            ///////Name
          
             try{
            
            
            
            String sqlSearch = "SELECT * FROM teacher_information";
            
            prepstmnt = con.prepareStatement(sqlSearch);
            res=prepstmnt.executeQuery();
            
            while(res.next())
                {
                Name = res.getString("Teacher_Name");
                Desig = res.getString("Teacher_Desig");
                Mobile = res.getString("Teacher_Mobile");
                Email = res.getString("Teacher_Email");
                Add = res.getString("Teacher_Address");
                    
               
             
              
            }
            
            
            
        }catch(Exception e)
        {
            System.out.println("Error ==> "+e);
        }
             
             Paragraph Title = new Paragraph("Chittagong Polytechnic Institute", new Font(Font.BOLD, 40, Font.BOLD,Color.DARK_GRAY));
            Title.setAlignment(Element.ALIGN_CENTER);
            document.add(Title);
            Paragraph Subtitle = new Paragraph("Nasirabad, Chittagong - 4209", new Font(Font.BOLD, 20, Font.BOLD,Color.DARK_GRAY));
            Subtitle.setAlignment(Element.ALIGN_CENTER);
            document.add(Subtitle);

            Paragraph mainparagraph = new Paragraph("Teacher's Information", new Font(Font.BOLD, 30, Font.BOLD,Color.DARK_GRAY));
            mainparagraph.setAlignment(Element.ALIGN_CENTER);
            
            

     
            
            PdfPTable my_report_table1 = new PdfPTable(2);
            
            //left side
            PdfPCell table_cell1 = new PdfPCell();
            my_report_table1.setWidthPercentage(100);

            table_cell1 = new PdfPCell(new Phrase(" ", new Font(Font.NORMAL, 15, Font.BOLD)));
            table_cell1.setHorizontalAlignment(Element.ALIGN_LEFT);
            // table_cell1.setBorder(1);
            

            table_cell1.setBorder(com.lowagie.text.Rectangle.NO_BORDER);
            //table_cell1.setBorder(Rectangle.BOX);
            my_report_table1.addCell(table_cell1);

            //right side
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MMM-yyyy hh:mm:ss a");
            java.util.Date printDate = new java.util.Date();
            dateFormat.format(printDate);
           
            table_cell1 = new PdfPCell(new Phrase("Print Date & Time :  " + dateFormat.format(printDate), new Font(Font.NORMAL, 11, Font.BOLD)));
            table_cell1.setHorizontalAlignment(Element.ALIGN_RIGHT);
            //table_cell6.setBorder(Rectangle.NO_BORDER);
            
            table_cell1.setBorder(com.lowagie.text.Rectangle.NO_BORDER);
            my_report_table1.addCell(table_cell1);
                                 

            //TABLE HEADER
            PdfPTable my_report_table = new PdfPTable(5);
            float[] columnWidths = {0.5f,0.8f,0.8f,0.8f,0.8f};
            my_report_table.setWidths(columnWidths);
            my_report_table.setWidthPercentage(100);
            String[] headers1 = new String[]{
                "Name","Designation","Mobile", "Email", "Address"
            };

            PdfPTable table1 = new PdfPTable(headers1.length);
            table1.setWidths(columnWidths);
            table1.setWidthPercentage(100);
            for (String header : headers1) {
                PdfPCell cell = new PdfPCell();

                cell.setGrayFill(0.9f);
                cell.setPhrase(new Phrase(header, new Font(Font.NORMAL, 15, Font.BOLD)));
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                table1.addCell(cell);
            }
            table1.completeRow();
            
            ////END OF HEADER
            
            ///////////////
            
            PdfPTable my_report_table2 = new PdfPTable(5);
            
            //left side
            PdfPCell table_cell2 = new PdfPCell();
            my_report_table2.setWidthPercentage(100);         
            my_report_table2.setWidths(columnWidths);

            
            ///////////////////
            
              try {

            
            //String sqlQry="Select * from emp_info ORDER BY Emp_ID ASC";
           String sqlSearch = "SELECT * FROM teacher_information";

            prepstmnt = con.prepareStatement(sqlSearch);
            res=prepstmnt.executeQuery();
            
            while(res.next())
            {
                
            Name=res.getString("Teacher_Name");  
            table_cell2 = new PdfPCell(new Phrase(Name, new Font(Font.NORMAL, 15, Font.BOLD)));
            table_cell2.setHorizontalAlignment(Element.ALIGN_CENTER);
            // table_cell1.setBorder(1);           
           // table_cell2.setBorder(Rectangle.NO_BORDER);
            //table_cell1.setBorder(Rectangle.BOX);
            my_report_table2.addCell(table_cell2);
            
            Desig = res.getString("Teacher_Desig");
             table_cell2 = new PdfPCell(new Phrase(Desig, new Font(Font.NORMAL, 15, Font.BOLD)));
            table_cell2.setHorizontalAlignment(Element.ALIGN_CENTER);
            // table_cell1.setBorder(1);           
           // table_cell2.setBorder(Rectangle.NO_BORDER);
            //table_cell1.setBorder(Rectangle.BOX);
            my_report_table2.addCell(table_cell2);
            
            Mobile = res.getString("Teacher_Mobile");
             table_cell2 = new PdfPCell(new Phrase(Mobile, new Font(Font.NORMAL, 15, Font.BOLD)));
            table_cell2.setHorizontalAlignment(Element.ALIGN_CENTER);
            // table_cell1.setBorder(1);           
           // table_cell2.setBorder(Rectangle.NO_BORDER);
            //table_cell1.setBorder(Rectangle.BOX);
            my_report_table2.addCell(table_cell2);
            
            Email = res.getString("Teacher_Email");
            table_cell2 = new PdfPCell(new Phrase(Email, new Font(Font.NORMAL, 15, Font.BOLD)));
            table_cell2.setHorizontalAlignment(Element.ALIGN_CENTER);
            // table_cell1.setBorder(1);           
           // table_cell2.setBorder(Rectangle.NO_BORDER);
            //table_cell1.setBorder(Rectangle.BOX);
            my_report_table2.addCell(table_cell2);
            
            
            Add = res.getString("Teacher_Address");
            table_cell2 = new PdfPCell(new Phrase(Add, new Font(Font.NORMAL, 15, Font.BOLD)));
            table_cell2.setHorizontalAlignment(Element.ALIGN_CENTER);
            // table_cell1.setBorder(1);           
           // table_cell2.setBorder(Rectangle.NO_BORDER);
            //table_cell1.setBorder(Rectangle.BOX);
            my_report_table2.addCell(table_cell2);
            
            
             
                
               
                
            }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
           

           ///////////////

            document.add(mainparagraph);
            document.add(paragraph3);
            document.add(my_report_table1);
           
            document.add(paragraph3);
            document.add(table1);
            document.add(my_report_table2);
            
            
           

            // document.add(table);
        } catch (DocumentException | HeadlessException e56) {
            System.err.println(e56.getMessage());
        }

        document.close(); 
    }                                       
    
    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed
        try {
            print_Teachers_Information();
        } catch (SQLException | BadElementException | IOException ex) {
            Logger.getLogger(Panel_TeacherInformation.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if (Desktop.isDesktopSupported()) {
            try {
                File myfile = new File("Report.pdf");

                Desktop.getDesktop().open(myfile);
            } catch (IOException e17) {
                // JOptionPane.showMessageDialog(null, e17.toString());
            }
        }
    }//GEN-LAST:event_btnprintActionPerformed

    private void txt_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_SearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddnew;
    private javax.swing.JButton btnAttach;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSeach;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnprint;
    private javax.swing.JComboBox jComboDesignation;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel74;
    private javax.swing.JPanel jPanel75;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableTeacher;
    private javax.swing.JLabel lblTeacherimage;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txt_Search;
    private javax.swing.JTextArea txtareaaddress;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtimagepath;
    private javax.swing.JTextField txtmobile;
    // End of variables declaration//GEN-END:variables
}
