/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project_Panel;

import DatabaseConnection.DBConnectioncode;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Amin Kaiser
 */
public class Panel_Promote extends javax.swing.JPanel {

   //Variaable for Database Connection
    
    Connection con;
    PreparedStatement prepstmnt = null;
    ResultSet res = null;
    
    public Panel_Promote() {
        initComponents();
        
        try {
            con = DBConnectioncode.DBConnectioncode();

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Panel_Promote.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    public void TableRefresh()
    {
        try{
                DefaultTableModel tb = (DefaultTableModel)jTablepromotetable.getModel();
                int row=jTablepromotetable.getRowCount();
                for(int i=row-1;i>=0;i--)
                {
                    tb.removeRow(i);
                }
       
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    
    
    public void Refresh()
     {
         jComboBoxpromote.setSelectedItem("Select");
         jTextFieldName.setText("");
         jTextFieldRoll.setText("");
         jTextFieldReg.setText("");
         jComboBoxSession.setSelectedItem("Select");
         jComboBoxSemester.setSelectedItem("Select");
         jTextFieldCGPA.setText("");
         
     }
    
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel41 = new javax.swing.JPanel();
        jLabel146 = new javax.swing.JLabel();
        jComboBoxpromote = new javax.swing.JComboBox();
        jPanel123 = new javax.swing.JPanel();
        jLabel122 = new javax.swing.JLabel();
        jLabel123 = new javax.swing.JLabel();
        jLabel124 = new javax.swing.JLabel();
        jLabel125 = new javax.swing.JLabel();
        jLabel143 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldRoll = new javax.swing.JTextField();
        jTextFieldReg = new javax.swing.JTextField();
        jComboBoxSemester = new javax.swing.JComboBox();
        jComboBoxSession = new javax.swing.JComboBox();
        jLabel144 = new javax.swing.JLabel();
        jTextFieldCGPA = new javax.swing.JTextField();
        jPanel126 = new javax.swing.JPanel();
        jScrollPane19 = new javax.swing.JScrollPane();
        jTablepromotetable = new javax.swing.JTable();
        jPanel89 = new javax.swing.JPanel();
        jButtonSaveup = new javax.swing.JButton();
        jButton107 = new javax.swing.JButton();
        jButton116 = new javax.swing.JButton();
        jButton117 = new javax.swing.JButton();
        jButton118 = new javax.swing.JButton();
        jButton119 = new javax.swing.JButton();
        jLabel145 = new javax.swing.JLabel();
        jComboBoxpromotion = new javax.swing.JComboBox<>();
        jComboBox55 = new javax.swing.JComboBox<>();

        jPanel41.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel146.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel146.setText("Select Semester :");

        jComboBoxpromote.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jComboBoxpromote.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "1st Semester", "2nd Semester", "3rd Semester", "4th Semester", "5th Semester", "6th Semester", "7th Semester", "8th Semester" }));
        jComboBoxpromote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxpromoteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel41Layout = new javax.swing.GroupLayout(jPanel41);
        jPanel41.setLayout(jPanel41Layout);
        jPanel41Layout.setHorizontalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel41Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel146, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxpromote, 0, 204, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel41Layout.setVerticalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel41Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel146, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxpromote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel123.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel122.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel122.setText("Name :");

        jLabel123.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel123.setText("Roll :");

        jLabel124.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel124.setText("Reg. No :");

        jLabel125.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel125.setText("Session :");

        jLabel143.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel143.setText("CGPA :");

        jTextFieldName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jTextFieldRoll.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jTextFieldReg.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jComboBoxSemester.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jComboBoxSemester.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "1st Semester", "2nd Semester", "3rd Semester", "4th Semester", "5th Semester", "6th Semester", "7th Semester", "8th Semester", "EX- Semester" }));

        jComboBoxSession.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jComboBoxSession.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "2012-2013", "2013-2014", "2014-2015", "2015-2016", "2016-2017", "2017-2018", "2018-2019", "2019-2020", "2020-2021", "2021-2022" }));

        jLabel144.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel144.setText("Semester :");

        jTextFieldCGPA.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel123Layout = new javax.swing.GroupLayout(jPanel123);
        jPanel123.setLayout(jPanel123Layout);
        jPanel123Layout.setHorizontalGroup(
            jPanel123Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel123Layout.createSequentialGroup()
                .addGroup(jPanel123Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel123Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel143, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldCGPA, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel123Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel123Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel123Layout.createSequentialGroup()
                                .addComponent(jLabel122, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel123Layout.createSequentialGroup()
                                .addComponent(jLabel123, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jTextFieldRoll, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel123Layout.createSequentialGroup()
                                .addComponent(jLabel124, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jTextFieldReg, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel123Layout.createSequentialGroup()
                                .addComponent(jLabel125, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jComboBoxSession, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel123Layout.createSequentialGroup()
                                .addComponent(jLabel144, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jComboBoxSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel123Layout.setVerticalGroup(
            jPanel123Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel123Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel123Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel122, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel123Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel123, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldRoll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel123Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel124, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel123Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel125, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxSession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel123Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel144, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel123Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel143, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCGPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel126.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTablepromotetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "   Select", "   Name", "   Roll ", "   Reg. No", "   Session ", "   Semester  ", "   CGPA "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane19.setViewportView(jTablepromotetable);

        javax.swing.GroupLayout jPanel126Layout = new javax.swing.GroupLayout(jPanel126);
        jPanel126.setLayout(jPanel126Layout);
        jPanel126Layout.setHorizontalGroup(
            jPanel126Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel126Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel126Layout.setVerticalGroup(
            jPanel126Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel126Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane19, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel89.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonSaveup.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSaveup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Panel/save2.png"))); // NOI18N
        jButtonSaveup.setText("Save");

        jButton107.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton107.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Panel/Trash-can16.png"))); // NOI18N
        jButton107.setText("Delete");

        jButton116.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton116.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Panel/Update.png"))); // NOI18N
        jButton116.setText("Update");

        jButton117.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton117.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Panel/Print.png"))); // NOI18N
        jButton117.setText("Print");

        jButton118.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton118.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Panel/refresh.png"))); // NOI18N
        jButton118.setText("Refresh");

        jButton119.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton119.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Panel/view.gif"))); // NOI18N
        jButton119.setText("Preview");

        javax.swing.GroupLayout jPanel89Layout = new javax.swing.GroupLayout(jPanel89);
        jPanel89.setLayout(jPanel89Layout);
        jPanel89Layout.setHorizontalGroup(
            jPanel89Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel89Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton119)
                .addGap(26, 26, 26)
                .addComponent(jButton117, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton118)
                .addContainerGap())
            .addGroup(jPanel89Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jButtonSaveup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton107)
                .addGap(18, 18, 18)
                .addComponent(jButton116)
                .addGap(22, 22, 22))
        );
        jPanel89Layout.setVerticalGroup(
            jPanel89Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel89Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel89Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSaveup, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton107, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton116, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel89Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton117, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton118, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton119, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel145.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel145.setText("Selected Student Send to :");

        jComboBoxpromotion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBoxpromotion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Promotion To", "2nd Semester", "3rd Semster", "4th Semester", "5th Semester", "6th Semester", "7th Semester", "8th Semster", "Passed From Institute" }));
        jComboBoxpromotion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxpromotionActionPerformed(evt);
            }
        });

        jComboBox55.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox55.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Drop To", "1st Semester", "2nd Semester", "3rd Semster", "4th Semester", "5th Semester", "6th Semester", "7th Semester", "8th Semster" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel123, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel89, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel126, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(401, 401, 401)
                        .addComponent(jLabel145)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxpromotion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox55, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jPanel123, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel89, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel126, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel145, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxpromotion, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jComboBox55))
                .addContainerGap(57, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxpromoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxpromoteActionPerformed
        
        Object Result = jComboBoxpromote.getSelectedItem();
        
        if("1st Semester"==Result)
        {
            try{
                DefaultTableModel tb = (DefaultTableModel)jTablepromotetable.getModel();
                String sqlSrch = "SELECT * FROM  student_information WHERE Stu_semester='"+Result+"'";
            
                     prepstmnt = con.prepareStatement(sqlSrch);
                     res = prepstmnt.executeQuery();
            
                    while(res.next())
                    {
                        String Name = res.getString("Stu_Name");
                        String roll = res.getString("Stu_Roll");
                        String reg = res.getString("Stu_RegNo");
                        String session = res.getString("Stu_Session");
                        String semester = res.getString("Stu_semester");

                        tb.addRow(new Object[]{false,Name,roll,reg,session,semester,""});

                    }
                
            }catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
            TableRefresh();
            try{
                DefaultTableModel tb = (DefaultTableModel)jTablepromotetable.getModel();
                String sqlSrch = "SELECT * FROM  student_information WHERE Stu_semester='"+Result+"'";
            
                     prepstmnt = con.prepareStatement(sqlSrch);
                     res = prepstmnt.executeQuery();
            
                    while(res.next())
                    {
                        String Name = res.getString("Stu_Name");
                        String roll = res.getString("Stu_Roll");
                        String reg = res.getString("Stu_RegNo");
                        String session = res.getString("Stu_Session");
                        String semester = res.getString("Stu_semester");

                        tb.addRow(new Object[]{false,Name,roll,reg,session,semester,""});

                    }
                
            }catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
           
            
        }
        
        
    }//GEN-LAST:event_jComboBoxpromoteActionPerformed

    private void jComboBoxpromotionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxpromotionActionPerformed
        
        DefaultTableModel tb = (DefaultTableModel) jTablepromotetable.getModel();
        Object ViewResult = jComboBoxpromotion.getSelectedItem();
        
        if("2nd Semester"==ViewResult)
        {
            //////////////////start of delete code
         try{
         for (int i = 0; i < tb.getRowCount(); i++){
                 
         String sqlDelete = "DELETE from first_semester_result where roll = '"+tb.getValueAt(i, 2).toString()+"'";
            
         PreparedStatement prepStmtd = con.prepareStatement(sqlDelete);
           
             
         prepStmtd.execute();
                 
         }            
         // JOptionPane.showMessageDialog(null, "Deleted!!!");
         }catch(SQLException | HeadlessException e)
         {
         //JOptionPane.showMessageDialog(null, e);
         }
         ///////////////////////end of delete code
            
            
            try {
            String sqlQry = "INSERT INTO first_semester_result(promotestatus,name,roll,reg,session,semester,cgpa) VALUES(?,?,?,?,?,?,?)";
            PreparedStatement prepStmts = con.prepareStatement(sqlQry);

            for (int i = 0; i < tb.getRowCount(); i++) {

                if ((tb.getValueAt(i, 0).toString().equals("true"))) { //start if condition

                    prepStmts.setString(1, tb.getValueAt(i, 0).toString());
                    prepStmts.setString(2, tb.getValueAt(i, 1).toString());
                    prepStmts.setString(3, tb.getValueAt(i, 2).toString());
                    prepStmts.setString(4, tb.getValueAt(i, 3).toString());
                    prepStmts.setString(5, tb.getValueAt(i, 4).toString());
                    prepStmts.setString(6, tb.getValueAt(i, 5).toString());
                    prepStmts.setString(7, tb.getValueAt(i, 6).toString());

                    prepStmts.execute();

               

            }
            }
            JOptionPane.showMessageDialog(this, "Updated");

        } catch (SQLException | HeadlessException e) {
          //  JOptionPane.showMessageDialog(this, e.getMessage());
        }
        }
        
        
        try{
         //for (int i = 0; i < tbmodel.getRowCount(); i++){
                 
         String sqlDelete = "DELETE from first_semester_result where promotestatus = 'false' ";
            
         PreparedStatement prepStmtd = con.prepareStatement(sqlDelete);
           
             
         prepStmtd.execute();
                 
         //  }
             
           
             
         // JOptionPane.showMessageDialog(null, "Deleted!!!");
         }catch(SQLException | HeadlessException e)
         {
         //JOptionPane.showMessageDialog(null, e);
         }
         
         ///////////////////////end of delete code
        
    }//GEN-LAST:event_jComboBoxpromotionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton107;
    private javax.swing.JButton jButton116;
    private javax.swing.JButton jButton117;
    private javax.swing.JButton jButton118;
    private javax.swing.JButton jButton119;
    private javax.swing.JButton jButtonSaveup;
    private javax.swing.JComboBox<String> jComboBox55;
    private javax.swing.JComboBox jComboBoxSemester;
    private javax.swing.JComboBox jComboBoxSession;
    private javax.swing.JComboBox jComboBoxpromote;
    private javax.swing.JComboBox<String> jComboBoxpromotion;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel143;
    private javax.swing.JLabel jLabel144;
    private javax.swing.JLabel jLabel145;
    private javax.swing.JLabel jLabel146;
    private javax.swing.JPanel jPanel123;
    private javax.swing.JPanel jPanel126;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel89;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JTable jTablepromotetable;
    private javax.swing.JTextField jTextFieldCGPA;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldReg;
    private javax.swing.JTextField jTextFieldRoll;
    // End of variables declaration//GEN-END:variables
}
